name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        node: [ 14, 16 ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run lint --if-present
      - run: npm run test --if-present
      - run: npm run coverage --if-present

