name: Release
on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      # - run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_PERSONAL_TOKEN }}
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
